---
- name: Write default/locale
  ansible.builtin.template:
    src: locale.j2
    dest: /etc/default/locale
    owner: root
    group: root
    mode: "0644"

- name: Write locale.gen
  ansible.builtin.template:
    src: locale.gen.j2
    dest: /etc/locale.gen
    owner: root
    group: root
    mode: "0644"
  notify:
    - Run locale-gen
